language: python

jobs:
  include:
    - name: linux
      os: linux
      language: python
      install:
        - python3 -m pip install targeted
      script:
        - python3 test.py

    # --------------------------------------------------------------------------------

    - name: osx
      os: osx
      language: shell
      install:
        - python3 -m pip install targeted
      script:
        - python3 test.py

    # --------------------------------------------------------------------------------
